/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlantCareRouteImport } from './routes/plant-care'
import { Route as NurseriesRouteImport } from './routes/nurseries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseHerbsRouteImport } from './routes/browse-herbs'
import { Route as BecomeASupplierRouteImport } from './routes/become-a-supplier'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseHerbsIndexRouteImport } from './routes/browse-herbs.index'
import { Route as BrowseHerbsSlugRouteImport } from './routes/browse-herbs.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantCareRoute = PlantCareRouteImport.update({
  id: '/plant-care',
  path: '/plant-care',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseriesRoute = NurseriesRouteImport.update({
  id: '/nurseries',
  path: '/nurseries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseHerbsRoute = BrowseHerbsRouteImport.update({
  id: '/browse-herbs',
  path: '/browse-herbs',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeASupplierRoute = BecomeASupplierRouteImport.update({
  id: '/become-a-supplier',
  path: '/become-a-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseHerbsIndexRoute = BrowseHerbsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseHerbsRoute,
} as any)
const BrowseHerbsSlugRoute = BrowseHerbsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrowseHerbsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-supplier': typeof BecomeASupplierRoute
  '/browse-herbs': typeof BrowseHerbsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/nurseries': typeof NurseriesRoute
  '/plant-care': typeof PlantCareRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/browse-herbs/$slug': typeof BrowseHerbsSlugRoute
  '/browse-herbs/': typeof BrowseHerbsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-supplier': typeof BecomeASupplierRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/nurseries': typeof NurseriesRoute
  '/plant-care': typeof PlantCareRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/browse-herbs/$slug': typeof BrowseHerbsSlugRoute
  '/browse-herbs': typeof BrowseHerbsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-supplier': typeof BecomeASupplierRoute
  '/browse-herbs': typeof BrowseHerbsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/nurseries': typeof NurseriesRoute
  '/plant-care': typeof PlantCareRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/browse-herbs/$slug': typeof BrowseHerbsSlugRoute
  '/browse-herbs/': typeof BrowseHerbsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-supplier'
    | '/browse-herbs'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/nurseries'
    | '/plant-care'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/browse-herbs/$slug'
    | '/browse-herbs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-supplier'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/nurseries'
    | '/plant-care'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/browse-herbs/$slug'
    | '/browse-herbs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-a-supplier'
    | '/browse-herbs'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/nurseries'
    | '/plant-care'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/browse-herbs/$slug'
    | '/browse-herbs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeASupplierRoute: typeof BecomeASupplierRoute
  BrowseHerbsRoute: typeof BrowseHerbsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  LoginRoute: typeof LoginRoute
  NurseriesRoute: typeof NurseriesRoute
  PlantCareRoute: typeof PlantCareRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant-care': {
      id: '/plant-care'
      path: '/plant-care'
      fullPath: '/plant-care'
      preLoaderRoute: typeof PlantCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurseries': {
      id: '/nurseries'
      path: '/nurseries'
      fullPath: '/nurseries'
      preLoaderRoute: typeof NurseriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-herbs': {
      id: '/browse-herbs'
      path: '/browse-herbs'
      fullPath: '/browse-herbs'
      preLoaderRoute: typeof BrowseHerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-supplier': {
      id: '/become-a-supplier'
      path: '/become-a-supplier'
      fullPath: '/become-a-supplier'
      preLoaderRoute: typeof BecomeASupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-herbs/': {
      id: '/browse-herbs/'
      path: '/'
      fullPath: '/browse-herbs/'
      preLoaderRoute: typeof BrowseHerbsIndexRouteImport
      parentRoute: typeof BrowseHerbsRoute
    }
    '/browse-herbs/$slug': {
      id: '/browse-herbs/$slug'
      path: '/$slug'
      fullPath: '/browse-herbs/$slug'
      preLoaderRoute: typeof BrowseHerbsSlugRouteImport
      parentRoute: typeof BrowseHerbsRoute
    }
  }
}

interface BrowseHerbsRouteChildren {
  BrowseHerbsSlugRoute: typeof BrowseHerbsSlugRoute
  BrowseHerbsIndexRoute: typeof BrowseHerbsIndexRoute
}

const BrowseHerbsRouteChildren: BrowseHerbsRouteChildren = {
  BrowseHerbsSlugRoute: BrowseHerbsSlugRoute,
  BrowseHerbsIndexRoute: BrowseHerbsIndexRoute,
}

const BrowseHerbsRouteWithChildren = BrowseHerbsRoute._addFileChildren(
  BrowseHerbsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeASupplierRoute: BecomeASupplierRoute,
  BrowseHerbsRoute: BrowseHerbsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  LoginRoute: LoginRoute,
  NurseriesRoute: NurseriesRoute,
  PlantCareRoute: PlantCareRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
